### ISSUE TITLE
Repositório CKANext DadosAbertos incorreto no README.rst

### ISSUE THREAD

**Issue by nettoclaudio** [thenets/ckanext-dadosabertos#1]
No passo "3. Instale o plugin CKANext DadosAbertos". O repositório que está sendo obtido de fato é o CKANext Pages, e não o CKANext DadosAbertos.

> 3. Instale o plugin CKANext DadosAbertos
> 
> | Command --- | --- 1 | su -s /bin/bash - ckan -c ". /usr/lib/ckan/default/bin/activate && pip install -e **git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages**" 2 | su -s /bin/bash - ckan -c ". /usr/lib/ckan/default/bin/activate && pip install -r /usr/lib/ckan/default/src/ckanext-dadosabertos/pip-requirements.txt" 3 | sed -i 's/dadosabertos/ /g' /etc/ckan/default/development.ini 4 | sed -i 's/stats text_view image_view recline_view/stats text_view image_view recline_view dadosabertos /g' /etc/ckan/default/development.ini 5 | su -s /bin/bash - ckan -c ". /usr/lib/ckan/default/bin/activate && cd /usr/lib/ckan/default/src/ckanext-dadosabertos && python setup.py develop"

Substitui por "**git+https://github.com/thenets/ckanext-dadosabertos.git#egg=ckanext-dadosabertos**", e funcionou corretamente.

**Comment by thenets** [comment]
Vlw, cara!
Esse arquivo de README continha um conteúdo antigo e só era mantido por conta da necessidade de existir um arquivo desse tipo para o Plugin funcionar.

Acabei de limpar o conteúdo dele, pra evitar confusões futuras.
